spring:
  redis:
    host: a9-redis-master
    password: 123456
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://a9-auth
          predicates:
            - Path=/user/login,/user/register
          filters:
            - StripPrefix=1
        - id: service
          uri: lb://a9-service
          predicates:
            - Path=/user/**,/article/**,/editor/**,/template/**
