version: '3.9'

services:
  a9-mongo:
    image: mongo:4.4.6
    container_name: a9-mongo
    volumes:
      - mongo_db:/data/db
      - mongo_backup:/data/backup
      - mongo_configdb:/data/configdb
    ports:
      - "27017:27017"

  a9-auth:
    container_name: a9-auth
    build:
      context: a9-auth
    ports:
      - "${A9_AUTH_PORT}:8080"
    depends_on:
      - a9-mongo
    links:
      - a9-mongo:a9-mongo

volumes:
  mongo_db:
    driver: local
  mongo_backup:
    driver: local
  mongo_configdb:
    driver: local
