spring:
  redis:
    host: a9-redis-master
    password: 123456
  data:
    mongodb:
      uri: mongodb://a9-mongo:27017/a9

jwt:
  algo:
    secret: cn-soft-bei-a9
  issuer: a9
  expiration: 36000  # 10 hours

oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5t6gFRY8vs2D9om9d9oV
  accessKeySecret: GgAeLHRAohJ7vQI5amZ8Z28fLRxi1V
  bucketName: tzq-oos-1
  rootPath: a9

tencent:
  secretId: AKID743pOioeFbiZBYgYBZicHgqkOnOlupVw
  secretKey: EDwQffQwDE0Wnoa7PSGp8C1bw1rey2pM
  endpoint: nlp.tencentcloudapi.com
  region: ap-guangzhou

baidu:
  access_token: 24.35eb3df6e6e417c802f56e29bb26c3f3.2592000.1661739800.282335-26580448

tg:
  url: http://a9-text-generation:8000